sudo: required
services: 
 - docker
before_install: 
 - docker build -t bestpessimist/react -f Dockerfile.dev .
script:
 - docker run -e CI=true bestpessimist/react npm run test -- --coverage
language: generic
